<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDeIxELU\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDeIxELU/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDeIxELU.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDeIxELU\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDeIxELU\App_KernelTestDebugContainer([
    'container.build_hash' => 'DeIxELU',
    'container.build_id' => 'd6673a92',
    'container.build_time' => 1711348433,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDeIxELU');
