<?php

namespace ContainerFhxTxQL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B6ePwvxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B6ePwvx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B6ePwvx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailService' => ['privates', 'App\\Application\\v1\\Service\\MailService', 'getMailServiceService', true],
        ], [
            'mailService' => 'App\\Application\\v1\\Service\\MailService',
        ]);
    }
}
