<?php

namespace Container4pDCgjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_DoctrineObjectConstructor_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.doctrine_object_constructor.inner' shared service.
     *
     * @return \JMS\Serializer\Construction\UnserializeObjectConstructor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/Construction/ObjectConstructorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/Construction/UnserializeObjectConstructor.php';

        return $container->privates['jms_serializer.doctrine_object_constructor.inner'] = new \JMS\Serializer\Construction\UnserializeObjectConstructor();
    }
}
