<?php

namespace ContainerDeIxELU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvGeneratorServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\v1\Service\CsvGeneratorService' shared autowired service.
     *
     * @return \App\Application\v1\Service\CsvGeneratorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/v1/Service/CsvGeneratorService.php';

        return $container->privates['App\\Application\\v1\\Service\\CsvGeneratorService'] = new \App\Application\v1\Service\CsvGeneratorService();
    }
}
