<?php

namespace ContainerDeIxELU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoricalQuotesControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Application\v1\Controller\HistoricalQuotesController' shared autowired service.
     *
     * @return \App\Application\v1\Controller\HistoricalQuotesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/v1/Controller/HistoricalQuotesController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/v1/Service/CsvGeneratorService.php';

        $container->services['App\\Application\\v1\\Controller\\HistoricalQuotesController'] = $instance = new \App\Application\v1\Controller\HistoricalQuotesController(($container->privates['validator'] ?? $container->load('getValidatorService')), ($container->privates['App\\Application\\v1\\Service\\FinanceDataService'] ?? $container->load('getFinanceDataServiceService')), ($container->privates['App\\Application\\v1\\Service\\CsvGeneratorService'] ??= new \App\Application\v1\Service\CsvGeneratorService()), ($container->privates['App\\Application\\v1\\Service\\MailService'] ?? $container->load('getMailServiceService')), ($container->privates['App\\Application\\v1\\Service\\RetrieveValidSymbolsService'] ?? $container->load('getRetrieveValidSymbolsServiceService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
        ], [
            'form.factory' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'twig' => '?',
        ]))->withContext('App\\Application\\v1\\Controller\\HistoricalQuotesController', $container));

        return $instance;
    }
}
