<?php

namespace ContainerDeIxELU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_Metadata_AnnotationOrAttributeDriverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'jms_serializer.metadata.annotation_or_attribute_driver' shared service.
     *
     * @return \JMS\Serializer\Metadata\Driver\AnnotationOrAttributeDriver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/jms/metadata/src/Driver/DriverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/Metadata/Driver/ExpressionMetadataTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/Metadata/Driver/AnnotationOrAttributeDriver.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/Type/ParserInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/Type/Parser.php';

        return $container->privates['jms_serializer.metadata.annotation_or_attribute_driver'] = new \JMS\Serializer\Metadata\Driver\AnnotationOrAttributeDriver(($container->privates['jms_serializer.serialized_name_annotation_strategy'] ?? $container->load('getJmsSerializer_SerializedNameAnnotationStrategyService')), ($container->privates['jms_serializer.type_parser'] ??= new \JMS\Serializer\Type\Parser()), NULL, NULL);
    }
}
