<?php

namespace ContainerDeIxELU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymbolsValidatorServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'symbols_validator_service' shared autowired service.
     *
     * @return \App\Application\v1\Validator\Constraints\IsValidSymbolValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Application/v1/Validator/Constraints/IsValidSymbolValidator.php';

        return $container->privates['symbols_validator_service'] = new \App\Application\v1\Validator\Constraints\IsValidSymbolValidator(($container->privates['valid_values_service'] ?? $container->load('getValidValuesServiceService')));
    }
}
