<?php

namespace Container5fXBhVz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoricalQuotesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Application\v1\Controller\HistoricalQuotesController' shared autowired service.
     *
     * @return \App\Application\v1\Controller\HistoricalQuotesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/v1/Controller/HistoricalQuotesController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/v1/Service/FinanceDataService.php';
        include_once \dirname(__DIR__, 4).'/src/Application/v1/Service/CsvGeneratorService.php';
        include_once \dirname(__DIR__, 4).'/src/Application/v1/Service/RetrieveValidSymbolsService.php';

        $a = ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService'));
        $b = ($container->services['cache.app'] ?? $container->load('getCache_AppService'));
        $c = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $container->services['App\\Application\\v1\\Controller\\HistoricalQuotesController'] = $instance = new \App\Application\v1\Controller\HistoricalQuotesController(($container->privates['validator'] ?? $container->load('getValidatorService')), new \App\Application\v1\Service\FinanceDataService($a, $b, $c), new \App\Application\v1\Service\CsvGeneratorService(), ($container->privates['App\\Application\\v1\\Service\\MailService'] ?? $container->load('getMailServiceService')), new \App\Application\v1\Service\RetrieveValidSymbolsService($a, $b, $c), $c);

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
        ], [
            'form.factory' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'twig' => '?',
        ]))->withContext('App\\Application\\v1\\Controller\\HistoricalQuotesController', $container));

        return $instance;
    }
}
